Models/Reserva.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace tallerbiblioteca.Models
{
    public class Reserva
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey("Ejemplar")]
        public int IdEjemplar { get; set; }
        public Ejemplar Ejemplar{get; set;}  =new();
        
        [ForeignKey("Usuario")]
        public int IdUsuario { get; set; }

        public Usuario Usuario {get; set;}  =new();
     
        public DateTime FechaReserva { get; set; }
        public string Estado { get; set; } = "";
    }
}

Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using tallerbiblioteca.Context;
using tallerbiblioteca.Migrations;
using tallerbiblioteca.Models;
using tallerbiblioteca.Services;

namespace tallerbiblioteca.Controllers
{
    [Authorize]
    public class ReservasController : Controller
    {

        private readonly BibliotecaDbContext _context;
        private readonly ReservasServices _ReservasServices;


        public ReservasController(BibliotecaDbContext context, ReservasServices reservasServices)
        {
            _context = context;
            _ReservasServices = reservasServices;
        }
        private void MensajeRespuestaValidacionPermiso(ResponseModel resultado)
        {

            TempData["Mensaje"] = JsonConvert.SerializeObject(resultado);
        }

        // GET: Reserva
        public async Task<IActionResult> Index(string? buscar, DateTime? fecha, int pagina = 1, int itemsPagina = 5, int? id = null)
        {
            var reservas = await _ReservasServices.ObtenerReservas();
            if (id != null)
            {
                var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);

                if (User.IsInRole("2") && userIdClaim != null)
                {
                    int userId = Convert.ToInt32(userIdClaim.Value);
                    reservas = await _ReservasServices.BuscarR(userId);
                }
            }
            if (buscar != null)
            {
                reservas = await _ReservasServices.Buscar(buscar);
            }
            else if (fecha.HasValue)
            {
                reservas = await _ReservasServices.Buscarporfecha(fecha.Value.Date);
            }
            int totalItems = reservas.Count;
            int totalPaginas = (int)Math.Ceiling((double)totalItems / itemsPagina);

            int indiceInicio = (pagina - 1) * itemsPagina;

            var reservacionesPaginadas = reservas
                .Skip(indiceInicio)
                .Take(itemsPagina)
                .ToList();


            var paginacion = new Paginacion<Reserva>(reservacionesPaginadas, totalPaginas, pagina, itemsPagina);

            return View(paginacion);
        }
        public async Task<IActionResult> Create()
        {
            var ejemplares = await _ReservasServices.buscarEj();
            var usuarios = await _ReservasServices.buscarUs();

            var ejemplaresSelect = new SelectList(ejemplares, "Id", "Libro.Nombre");
            var usuariosSelectList = new SelectList(usuarios, "Id", "Name");
            ViewBag.Usuarios = usuariosSelectList;
            ViewBag.ejemplares = ejemplaresSelect;

            return View();
        }


        // POST: Reserva/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Reserva reserva)
        {
            bool buscreserva = await _ReservasServices.Encontrarreserva(reserva.IdUsuario);
            if (buscreserva)
            {
                TempData["ReservaPendiente"] = "True";
                return RedirectToAction("Catalog", "Libros");
            }
            MensajeRespuestaValidacionPermiso(await _ReservasServices.Crear(reserva, User));
            return RedirectToAction(nameof(Index));


        }

        // GET: Reserva/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var reserva = await _ReservasServices.enviarR(id);
            return View(reserva);
        }

        // POST: Reserva/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Eliminar = await _ReservasServices.Cambiarestado(id, User);
            MensajeRespuestaValidacionPermiso(await _ReservasServices.Cambiarestado(id, User));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Rechazadas(int pagina = 1, int itemsPagina = 5)
        {
            var eliminadas = await _ReservasServices.Rechazadas();
            int totalItems = eliminadas.Count;
            int totalPaginas = (int)Math.Ceiling((double)totalItems / itemsPagina);

            int indiceInicio = (pagina - 1) * itemsPagina;

            var reservacionesPaginadas = eliminadas
                .Skip(indiceInicio)
                .Take(itemsPagina)
                .ToList();
            var paginacion = new Paginacion<Reserva>(reservacionesPaginadas, totalPaginas, pagina, itemsPagina);

            return View(paginacion);

        }
    }
}

Views/Reservas/Create.cshtml
@model tallerbiblioteca.Models.Reserva
@using System.Security.Claims;
<h1>Create</h1>
<h4>Reserva</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Reservas"method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdEjemplar" class="control-label"></label>
                <select asp-for="IdEjemplar" class="form-control" asp-items="ViewBag.Ejemplares"></select>
                <span asp-validation-for="IdEjemplar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdUsuario" class="control-label"></label>
                <select asp-for="IdUsuario" class="form-control" asp-items="ViewBag.Usuarios"></select>
                <span asp-validation-for="IdUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script>
    $(document).ready(function () {
        $("form").submit(function () {
            console.log("IdEjemplar:", $("#IdEjemplar").val());
            console.log("IdUsuario:", $("#IdUsuario").val());
        });
    });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
     
    }
        
    }

@{
    Html.RenderPartial("~/Views/Redirigir.cshtml");
}

Views/Reservas/Delete.cshtml
@model tallerbiblioteca.Models.Reserva

@{
    ViewData["Title"] = "Rechazar";
}
<div style="color:black">
<h1>Rechazar reserva</h1>

<h3>¿Seguro deseas rechazar esta reserva?</h3>
<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEjemplar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEjemplar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaReserva)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaReserva)
        </dd>
   
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" >Rechazar</button> |
        <button><a asp-action="Index">Volver</a></button>
    </form>
</div>
</div>

Views/Reservas/Details.cshtml
@*@model tallerbiblioteca.Models.Reservas

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEjemplar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEjemplar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaReserva)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaReserva)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
*@

Views/Reservas/Edit.cshtml
@model tallerbiblioteca.Models.Reserva

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reserva</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdEjemplar" class="control-label"></label>
                <input asp-for="IdEjemplar" class="form-control" />
                <span asp-validation-for="IdEjemplar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdUsuario" class="control-label"></label>
                <input asp-for="IdUsuario" class="form-control" />
                <span asp-validation-for="IdUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaReserva" class="control-label"></label>
                <input asp-for="FechaReserva" class="form-control" />
                <span asp-validation-for="FechaReserva" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reservas/Index.cshtml
@using System.Security.Claims;
@using tallerbiblioteca.Controllers
@model Paginacion<Reserva>;
<div class="row" style="color: black">
    @if (User.FindFirst(ClaimTypes.Role)?.Value == "1")
    {
        <div class="col-4 justify-content-between">
            <div class="mt-2">
                <button><a asp-action="Create">Crear Reserva</a></button>
                <button><a asp-action="Rechazadas">Rechazadas</a></button>
                <form asp-controller="/Pdf" asp-action="GenerarPdfReservas" method="post" class="mt-2">
                    <button type="submit">Generar reporte</button>
                </form>
            </div>
        </div>
          <div class="col-4 justify-content-between">
            <form asp-action="Index" class="d-flex">

                <div class="col-md-4">
                    <label for="buscar" class="form-label">Búsqueda:</label>
                    <input class="form-control mr-2" type="text" id="buscar" name="buscar" placeholder="Primer Nombre - libro">
                        <label for="fecha" class="form-label">Día</label>
                        <input class="form-control" type="date" id="fecha" name="fecha">
                    <button class="mt-2" type="submit" style="color: black"> Buscar</button>
                  
                </div>
            </form>
            </div>
        
        }
     </div>    
<span class="input-border"></span>
<table class="mt-2">
    <thead>
        <tr>
            <th>Ejemplar</th>
            <th>
               Usuario
            </th>
            <th>
                Fecha
            </th>
            <th>
                Estado
            </th>
            @if (User.FindFirst(ClaimTypes.Role)?.Value == "1")
    {
            <th>Acción</th>
    }
        </tr>
    </thead>
    <tbody>
 <div style="color: black">
@foreach (var item in Model.Items) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ejemplar.Libro.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.Name) @Html.DisplayFor(modelItem => item.Usuario.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaReserva)
            </td>
                <td>
                    @{
                        string color;
                        if (item.Estado == "RECHAZADA")
                        {
                            color = "red";
                        }
                        else
                        {
                            color = "green";
                        }
                    }
                    <span style="color: @color;">@item.Estado</span>
                </td>
                
                    @if (User.FindFirst(ClaimTypes.Role)?.Value == "1")
                    {
                        <td>
                        <div class="flex"></div>
                        @if (item.Estado == "ACTIVO")
                        {
                            <form id="myForm" asp-controller="Peticiones" asp-action="Registrar" method="post">
                                <input type="hidden" name="Id_ejemplar" value="@item.IdEjemplar">
                                <input type="hidden" name="motivo" value="Prestamo Libro">
                                <input type="hidden" name="Id_usuario" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)">
                                <span class="fa-solid fa-circle-check fa-2xl" style="color: #83B440; cursor: pointer;"></span>
                                <a asp-action="Delete" class="fa-solid fa-xmark fa-2xl" style="color: #fa0000;" asp-route-id="@item.Id"></a>
                            </form>
                        }
                    </td>
                    }

                
        </tr>
}
        </div>
        
    </tbody>
</table>
<div class="pagination p1">
    <ul>
        <a style="width:80px;" class="page-link text-dark me-1" href="?pagina=1&busqueda=@Context.Request.Query["busqueda"]">Primera</a>
        <a href="?pagina=@(Model.Numero_pagina - 1)&busqueda=@Context.Request.Query["busqueda"]">
        <li><<</li></a>
        @for (var i = 1; i <= Model.TotalItems; i++)
        {

            <a class=" me-1 @(Model.Numero_pagina == i ? " is-active" : "") " href="?pagina=@i&busqueda=@Context.Request.Query["busqueda"]">@i</a>

        }
        @if (Model.Numero_pagina < Model.TotalItems)
        {

            <a href="?pagina=@(Model.Numero_pagina+ 1)&busqueda=@Context.Request.Query["busqueda"]">>></a>

        }
        <a class="ms-1" href="?pagina=@Model.TotalItems&busqueda=@Context.Request.Query["busqueda"]">
        <li>Fin</li></a>
    </ul>
</div>
@if (TempData["ReservaPentiende"] != null && TempData["ReservaPentiende"].ToString() == "True")
{
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            Swal.fire({
                icon: 'error',
                title: 'Error al reservar',
                text: 'Ya tienes una reserva pendiente, no puedes tener dos',
                showConfirmButton: true,
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = '@Url.Action("Catalog", "Libros")';  // Reemplaza 'NombreController' con el nombre real de tu controlador
                }
            });
        });
    </script>
}
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    @{
        var Mensaje = TempData["Mensaje"] as string;

        if (Mensaje != null)
        {
            var mensaje = Newtonsoft.Json.JsonConvert.DeserializeObject<ResponseModel>(Mensaje);
            <script>
                console.log("se va mostrar");

                const cuerpo = `@Html.Raw(Newtonsoft.Json.JsonConvert.ToString(mensaje.Mensaje))`;
                const icono = "@mensaje.Icono";
                MostrarMensajeUsuarios(icono, cuerpo);
            </script>

        }
        <script>
            const myForm = document.getElementById("myForm");
            const triggerElement = document.querySelector(".fa-circle-check");

            triggerElement.addEventListener("click", () => {
                myForm.submit();
            });

        </script>
    }
    }

Views/Reservas/Rechazadas.cshtml
@using System.Security.Claims;
@using tallerbiblioteca.Controllers
@model Paginacion<Reserva>;
<script>
    var userRole = '@User.FindFirstValue(ClaimTypes.Role)';

    if (userRole !== '1') {
        window.location.href = '/Libros/Catalog';
    }
</script>
<div style="color: black">

<h1>Reservas rechazadas</h1>

<p>
        <button><a asp-action="Index" class="btn"></a>Volver</button>
</p>
</div>
<table class="mt-2">
    <thead>
        <tr>
            <th>Libro</th>
            <th>
                Usuario
            </th>
            <th>
                FechaReserva
            </th>
            <th>
                Estado
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ejemplar.Libro.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Usuario.Name) @Html.DisplayFor(modelItem => item.Usuario.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaReserva)
                </td>
                <td>
                    <span style="color: red">@item.Estado</span>
                </td>
                
            </tr>
        }
    </tbody>
</table>
<div class="pagination p1">
    <ul>
        <a style="width:80px;" class="page-link text-dark me-1" href="?pagina=1&busqueda=@Context.Request.Query["busqueda"]">Primera</a>
        <a href="?pagina=@(Model.Numero_pagina - 1)&busqueda=@Context.Request.Query["busqueda"]">
        <li><<</li></a>
        @for (var i = 1; i <= Model.TotalItems; i++)
        {

            <a class=" me-1 @(Model.Numero_pagina == i ? " is-active" : "") " href="?pagina=@i&busqueda=@Context.Request.Query["busqueda"]">@i</a>

        }
        @if (Model.Numero_pagina < Model.TotalItems)
        {

            <a href="?pagina=@(Model.Numero_pagina + 1)&busqueda=@Context.Request.Query["busqueda"]">>></a>

        }
        <a class="ms-1" href="?pagina=@Model.TotalItems&busqueda=@Context.Request.Query["busqueda"]">
        <li>Fin</li></a>
    </ul>
</div>